vich_uploader:
    db_driver: orm

    mappings:
        user_image:
            uri_prefix: /user_images
            upload_destination: '%kernel.project_dir%/public/images/user_images'
            namer: vich_uploader.namer_origname
